//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/grammarware/projects/engage/Engage/parsing/Engage.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Engage.parsing {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.CLSCompliant(false)]
public partial class EngageParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		ID=32, QUOTED=33, WHITESPACE=34, NEWLINE=35, COMMENT=36;
	public const int
		RULE_engSpec = 0, RULE_typeDecl = 1, RULE_superType = 2, RULE_tokenDecl = 3, 
		RULE_lexeme = 4, RULE_handlerDecl = 5, RULE_trigger = 6, RULE_reaction = 7, 
		RULE_name = 8, RULE_assignment = 9, RULE_operation = 10;
	public static readonly string[] ruleNames = {
		"engSpec", "typeDecl", "superType", "tokenDecl", "lexeme", "handlerDecl", 
		"trigger", "reaction", "name", "assignment", "operation"
	};

	private static readonly string[] _LiteralNames = {
		null, "'namespace'", "'types'", "'tokens'", "'handlers'", "','", "'<:'", 
		"';'", "'::'", "'number'", "'string'", "'->'", "'where'", "'EOF'", "'upon'", 
		"'push'", "'('", "')'", "'wrap'", "'lift'", "'drop'", "'trim'", "'*'", 
		"'pass'", "':='", "'pop'", "'pop*'", "'pop#'", "'await'", "'with'", "'await*'", 
		"'tear'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, "ID", "QUOTED", "WHITESPACE", 
		"NEWLINE", "COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Engage.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static EngageParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public EngageParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public EngageParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class EngSpecContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(EngageParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeDeclContext[] typeDecl() {
			return GetRuleContexts<TypeDeclContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeDeclContext typeDecl(int i) {
			return GetRuleContext<TypeDeclContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TokenDeclContext[] tokenDecl() {
			return GetRuleContexts<TokenDeclContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TokenDeclContext tokenDecl(int i) {
			return GetRuleContext<TokenDeclContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public HandlerDeclContext[] handlerDecl() {
			return GetRuleContexts<HandlerDeclContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public HandlerDeclContext handlerDecl(int i) {
			return GetRuleContext<HandlerDeclContext>(i);
		}
		public EngSpecContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_engSpec; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.EnterEngSpec(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.ExitEngSpec(this);
		}
	}

	[RuleVersion(0)]
	public EngSpecContext engSpec() {
		EngSpecContext _localctx = new EngSpecContext(Context, State);
		EnterRule(_localctx, 0, RULE_engSpec);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 22; Match(T__0);
			State = 23; Match(ID);
			State = 24; Match(T__1);
			State = 28;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==ID) {
				{
				{
				State = 25; typeDecl();
				}
				}
				State = 30;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 31; Match(T__2);
			State = 35;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__8) | (1L << T__9) | (1L << QUOTED))) != 0)) {
				{
				{
				State = 32; tokenDecl();
				}
				}
				State = 37;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 38; Match(T__3);
			State = 42;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__12) | (1L << ID) | (1L << QUOTED))) != 0)) {
				{
				{
				State = 39; handlerDecl();
				}
				}
				State = 44;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeDeclContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(EngageParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(EngageParser.ID, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SuperTypeContext superType() {
			return GetRuleContext<SuperTypeContext>(0);
		}
		public TypeDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeDecl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.EnterTypeDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.ExitTypeDecl(this);
		}
	}

	[RuleVersion(0)]
	public TypeDeclContext typeDecl() {
		TypeDeclContext _localctx = new TypeDeclContext(Context, State);
		EnterRule(_localctx, 2, RULE_typeDecl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 45; Match(ID);
			State = 50;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__4) {
				{
				{
				State = 46; Match(T__4);
				State = 47; Match(ID);
				}
				}
				State = 52;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 55;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__5) {
				{
				State = 53; Match(T__5);
				State = 54; superType();
				}
			}

			State = 57; Match(T__6);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SuperTypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(EngageParser.ID, 0); }
		public SuperTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_superType; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.EnterSuperType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.ExitSuperType(this);
		}
	}

	[RuleVersion(0)]
	public SuperTypeContext superType() {
		SuperTypeContext _localctx = new SuperTypeContext(Context, State);
		EnterRule(_localctx, 4, RULE_superType);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 59; Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TokenDeclContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public LexemeContext[] lexeme() {
			return GetRuleContexts<LexemeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public LexemeContext lexeme(int i) {
			return GetRuleContext<LexemeContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(EngageParser.ID, 0); }
		public TokenDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tokenDecl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.EnterTokenDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.ExitTokenDecl(this);
		}
	}

	[RuleVersion(0)]
	public TokenDeclContext tokenDecl() {
		TokenDeclContext _localctx = new TokenDeclContext(Context, State);
		EnterRule(_localctx, 6, RULE_tokenDecl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 61; lexeme();
			State = 66;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__4) {
				{
				{
				State = 62; Match(T__4);
				State = 63; lexeme();
				}
				}
				State = 68;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 69; Match(T__7);
			State = 70; Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LexemeContext : ParserRuleContext {
		public IToken Q;
		public IToken N;
		public IToken S;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode QUOTED() { return GetToken(EngageParser.QUOTED, 0); }
		public LexemeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_lexeme; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.EnterLexeme(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.ExitLexeme(this);
		}
	}

	[RuleVersion(0)]
	public LexemeContext lexeme() {
		LexemeContext _localctx = new LexemeContext(Context, State);
		EnterRule(_localctx, 8, RULE_lexeme);
		try {
			State = 75;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case QUOTED:
				EnterOuterAlt(_localctx, 1);
				{
				State = 72; _localctx.Q = Match(QUOTED);
				}
				break;
			case T__8:
				EnterOuterAlt(_localctx, 2);
				{
				State = 73; _localctx.N = Match(T__8);
				}
				break;
			case T__9:
				EnterOuterAlt(_localctx, 3);
				{
				State = 74; _localctx.S = Match(T__9);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HandlerDeclContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TriggerContext trigger() {
			return GetRuleContext<TriggerContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ReactionContext reaction() {
			return GetRuleContext<ReactionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentContext[] assignment() {
			return GetRuleContexts<AssignmentContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentContext assignment(int i) {
			return GetRuleContext<AssignmentContext>(i);
		}
		public HandlerDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_handlerDecl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.EnterHandlerDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.ExitHandlerDecl(this);
		}
	}

	[RuleVersion(0)]
	public HandlerDeclContext handlerDecl() {
		HandlerDeclContext _localctx = new HandlerDeclContext(Context, State);
		EnterRule(_localctx, 10, RULE_handlerDecl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 77; trigger();
			State = 78; Match(T__10);
			State = 79; reaction();
			State = 89;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__11) {
				{
				State = 80; Match(T__11);
				State = 81; assignment();
				State = 86;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__4) {
					{
					{
					State = 82; Match(T__4);
					State = 83; assignment();
					}
					}
					State = 88;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TriggerContext : ParserRuleContext {
		public IToken T;
		public IToken Eof;
		public IToken NT;
		public IToken Flag;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode QUOTED() { return GetToken(EngageParser.QUOTED, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(EngageParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(EngageParser.ID, i);
		}
		public TriggerContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_trigger; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.EnterTrigger(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.ExitTrigger(this);
		}
	}

	[RuleVersion(0)]
	public TriggerContext trigger() {
		TriggerContext _localctx = new TriggerContext(Context, State);
		EnterRule(_localctx, 12, RULE_trigger);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 94;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case QUOTED:
				{
				State = 91; _localctx.T = Match(QUOTED);
				}
				break;
			case T__12:
				{
				State = 92; _localctx.Eof = Match(T__12);
				}
				break;
			case ID:
				{
				State = 93; _localctx.NT = Match(ID);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 98;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__13) {
				{
				State = 96; Match(T__13);
				State = 97; _localctx.Flag = Match(ID);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReactionContext : ParserRuleContext {
		public IToken Command;
		public IToken Star;
		[System.Diagnostics.DebuggerNonUserCode] public NameContext name() {
			return GetRuleContext<NameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(EngageParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(EngageParser.ID, i);
		}
		public ReactionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_reaction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.EnterReaction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.ExitReaction(this);
		}
	}

	[RuleVersion(0)]
	public ReactionContext reaction() {
		ReactionContext _localctx = new ReactionContext(Context, State);
		EnterRule(_localctx, 14, RULE_reaction);
		int _la;
		try {
			State = 138;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__14:
				EnterOuterAlt(_localctx, 1);
				{
				State = 100; _localctx.Command = Match(T__14);
				State = 101; name();
				State = 112;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__15) {
					{
					State = 102; Match(T__15);
					State = 103; Match(ID);
					State = 108;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__4) {
						{
						{
						State = 104; Match(T__4);
						State = 105; Match(ID);
						}
						}
						State = 110;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					State = 111; Match(T__16);
					}
				}

				}
				break;
			case T__17:
				EnterOuterAlt(_localctx, 2);
				{
				State = 114; _localctx.Command = Match(T__17);
				State = 115; name();
				State = 126;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__15) {
					{
					State = 116; Match(T__15);
					State = 117; Match(ID);
					State = 122;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__4) {
						{
						{
						State = 118; Match(T__4);
						State = 119; Match(ID);
						}
						}
						State = 124;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					State = 125; Match(T__16);
					}
				}

				}
				break;
			case T__18:
				EnterOuterAlt(_localctx, 3);
				{
				State = 128; _localctx.Command = Match(T__18);
				State = 129; Match(ID);
				}
				break;
			case T__19:
				EnterOuterAlt(_localctx, 4);
				{
				State = 130; _localctx.Command = Match(T__19);
				State = 131; Match(ID);
				}
				break;
			case T__20:
				EnterOuterAlt(_localctx, 5);
				{
				State = 132; _localctx.Command = Match(T__20);
				State = 133; Match(ID);
				State = 135;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__21) {
					{
					State = 134; _localctx.Star = Match(T__21);
					}
				}

				}
				break;
			case T__22:
				EnterOuterAlt(_localctx, 6);
				{
				State = 137; _localctx.Command = Match(T__22);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(EngageParser.ID, 0); }
		public NameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_name; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.EnterName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.ExitName(this);
		}
	}

	[RuleVersion(0)]
	public NameContext name() {
		NameContext _localctx = new NameContext(Context, State);
		EnterRule(_localctx, 16, RULE_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 140; Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(EngageParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public OperationContext operation() {
			return GetRuleContext<OperationContext>(0);
		}
		public AssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.EnterAssignment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.ExitAssignment(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentContext assignment() {
		AssignmentContext _localctx = new AssignmentContext(Context, State);
		EnterRule(_localctx, 18, RULE_assignment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 142; Match(ID);
			State = 143; Match(T__23);
			State = 144; operation();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperationContext : ParserRuleContext {
		public IToken Command;
		public IToken Name;
		public IToken ExtraContext;
		public IToken LocalContext;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(EngageParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(EngageParser.ID, i);
		}
		public OperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.EnterOperation(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEngageListener typedListener = listener as IEngageListener;
			if (typedListener != null) typedListener.ExitOperation(this);
		}
	}

	[RuleVersion(0)]
	public OperationContext operation() {
		OperationContext _localctx = new OperationContext(Context, State);
		EnterRule(_localctx, 20, RULE_operation);
		int _la;
		try {
			State = 173;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__24:
				EnterOuterAlt(_localctx, 1);
				{
				State = 146; _localctx.Command = Match(T__24);
				State = 147; _localctx.Name = Match(ID);
				}
				break;
			case T__25:
				EnterOuterAlt(_localctx, 2);
				{
				State = 148; _localctx.Command = Match(T__25);
				State = 149; _localctx.Name = Match(ID);
				}
				break;
			case T__26:
				EnterOuterAlt(_localctx, 3);
				{
				State = 150; _localctx.Command = Match(T__26);
				State = 151; _localctx.Name = Match(ID);
				}
				break;
			case T__27:
				EnterOuterAlt(_localctx, 4);
				{
				State = 152; _localctx.Command = Match(T__27);
				State = 159;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case ID:
					{
					{
					State = 153; _localctx.Name = Match(ID);
					}
					}
					break;
				case T__15:
					{
					{
					State = 154; Match(T__15);
					State = 155; _localctx.Name = Match(ID);
					State = 156; Match(T__13);
					State = 157; _localctx.ExtraContext = Match(ID);
					State = 158; Match(T__16);
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 163;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__28) {
					{
					State = 161; Match(T__28);
					State = 162; _localctx.LocalContext = Match(ID);
					}
				}

				}
				break;
			case T__29:
				EnterOuterAlt(_localctx, 5);
				{
				State = 165; _localctx.Command = Match(T__29);
				State = 166; _localctx.Name = Match(ID);
				State = 169;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__28) {
					{
					State = 167; Match(T__28);
					State = 168; _localctx.LocalContext = Match(ID);
					}
				}

				}
				break;
			case T__30:
				EnterOuterAlt(_localctx, 6);
				{
				State = 171; _localctx.Command = Match(T__30);
				State = 172; _localctx.Name = Match(ID);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '&', '\xB2', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\a', '\x2', '\x1D', '\n', '\x2', '\f', '\x2', '\xE', '\x2', ' ', 
		'\v', '\x2', '\x3', '\x2', '\x3', '\x2', '\a', '\x2', '$', '\n', '\x2', 
		'\f', '\x2', '\xE', '\x2', '\'', '\v', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\a', '\x2', '+', '\n', '\x2', '\f', '\x2', '\xE', '\x2', '.', '\v', '\x2', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', '\x33', '\n', '\x3', 
		'\f', '\x3', '\xE', '\x3', '\x36', '\v', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x5', '\x3', ':', '\n', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\a', '\x5', '\x43', 
		'\n', '\x5', '\f', '\x5', '\xE', '\x5', '\x46', '\v', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x5', '\x6', 'N', '\n', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\a', '\a', 'W', '\n', 
		'\a', '\f', '\a', '\xE', '\a', 'Z', '\v', '\a', '\x5', '\a', '\\', '\n', 
		'\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x5', '\b', '\x61', '\n', 
		'\b', '\x3', '\b', '\x3', '\b', '\x5', '\b', '\x65', '\n', '\b', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\a', '\t', 'm', '\n', '\t', '\f', '\t', '\xE', '\t', 'p', '\v', '\t', 
		'\x3', '\t', '\x5', '\t', 's', '\n', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\a', '\t', '{', '\n', '\t', 
		'\f', '\t', '\xE', '\t', '~', '\v', '\t', '\x3', '\t', '\x5', '\t', '\x81', 
		'\n', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', '\x8A', '\n', '\t', '\x3', 
		'\t', '\x5', '\t', '\x8D', '\n', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x5', '\f', '\xA2', '\n', '\f', '\x3', '\f', '\x3', '\f', '\x5', '\f', 
		'\xA6', '\n', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x5', '\f', '\xAC', '\n', '\f', '\x3', '\f', '\x3', '\f', '\x5', '\f', 
		'\xB0', '\n', '\f', '\x3', '\f', '\x2', '\x2', '\r', '\x2', '\x4', '\x6', 
		'\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x2', '\x2', 
		'\x2', '\xC5', '\x2', '\x18', '\x3', '\x2', '\x2', '\x2', '\x4', '/', 
		'\x3', '\x2', '\x2', '\x2', '\x6', '=', '\x3', '\x2', '\x2', '\x2', '\b', 
		'?', '\x3', '\x2', '\x2', '\x2', '\n', 'M', '\x3', '\x2', '\x2', '\x2', 
		'\f', 'O', '\x3', '\x2', '\x2', '\x2', '\xE', '`', '\x3', '\x2', '\x2', 
		'\x2', '\x10', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x12', '\x8E', '\x3', 
		'\x2', '\x2', '\x2', '\x14', '\x90', '\x3', '\x2', '\x2', '\x2', '\x16', 
		'\xAF', '\x3', '\x2', '\x2', '\x2', '\x18', '\x19', '\a', '\x3', '\x2', 
		'\x2', '\x19', '\x1A', '\a', '\"', '\x2', '\x2', '\x1A', '\x1E', '\a', 
		'\x4', '\x2', '\x2', '\x1B', '\x1D', '\x5', '\x4', '\x3', '\x2', '\x1C', 
		'\x1B', '\x3', '\x2', '\x2', '\x2', '\x1D', ' ', '\x3', '\x2', '\x2', 
		'\x2', '\x1E', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x1E', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '\x1F', '!', '\x3', '\x2', '\x2', '\x2', ' ', '\x1E', 
		'\x3', '\x2', '\x2', '\x2', '!', '%', '\a', '\x5', '\x2', '\x2', '\"', 
		'$', '\x5', '\b', '\x5', '\x2', '#', '\"', '\x3', '\x2', '\x2', '\x2', 
		'$', '\'', '\x3', '\x2', '\x2', '\x2', '%', '#', '\x3', '\x2', '\x2', 
		'\x2', '%', '&', '\x3', '\x2', '\x2', '\x2', '&', '(', '\x3', '\x2', '\x2', 
		'\x2', '\'', '%', '\x3', '\x2', '\x2', '\x2', '(', ',', '\a', '\x6', '\x2', 
		'\x2', ')', '+', '\x5', '\f', '\a', '\x2', '*', ')', '\x3', '\x2', '\x2', 
		'\x2', '+', '.', '\x3', '\x2', '\x2', '\x2', ',', '*', '\x3', '\x2', '\x2', 
		'\x2', ',', '-', '\x3', '\x2', '\x2', '\x2', '-', '\x3', '\x3', '\x2', 
		'\x2', '\x2', '.', ',', '\x3', '\x2', '\x2', '\x2', '/', '\x34', '\a', 
		'\"', '\x2', '\x2', '\x30', '\x31', '\a', '\a', '\x2', '\x2', '\x31', 
		'\x33', '\a', '\"', '\x2', '\x2', '\x32', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\x33', '\x36', '\x3', '\x2', '\x2', '\x2', '\x34', '\x32', '\x3', 
		'\x2', '\x2', '\x2', '\x34', '\x35', '\x3', '\x2', '\x2', '\x2', '\x35', 
		'\x39', '\x3', '\x2', '\x2', '\x2', '\x36', '\x34', '\x3', '\x2', '\x2', 
		'\x2', '\x37', '\x38', '\a', '\b', '\x2', '\x2', '\x38', ':', '\x5', '\x6', 
		'\x4', '\x2', '\x39', '\x37', '\x3', '\x2', '\x2', '\x2', '\x39', ':', 
		'\x3', '\x2', '\x2', '\x2', ':', ';', '\x3', '\x2', '\x2', '\x2', ';', 
		'<', '\a', '\t', '\x2', '\x2', '<', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'=', '>', '\a', '\"', '\x2', '\x2', '>', '\a', '\x3', '\x2', '\x2', '\x2', 
		'?', '\x44', '\x5', '\n', '\x6', '\x2', '@', '\x41', '\a', '\a', '\x2', 
		'\x2', '\x41', '\x43', '\x5', '\n', '\x6', '\x2', '\x42', '@', '\x3', 
		'\x2', '\x2', '\x2', '\x43', '\x46', '\x3', '\x2', '\x2', '\x2', '\x44', 
		'\x42', '\x3', '\x2', '\x2', '\x2', '\x44', '\x45', '\x3', '\x2', '\x2', 
		'\x2', '\x45', 'G', '\x3', '\x2', '\x2', '\x2', '\x46', '\x44', '\x3', 
		'\x2', '\x2', '\x2', 'G', 'H', '\a', '\n', '\x2', '\x2', 'H', 'I', '\a', 
		'\"', '\x2', '\x2', 'I', '\t', '\x3', '\x2', '\x2', '\x2', 'J', 'N', '\a', 
		'#', '\x2', '\x2', 'K', 'N', '\a', '\v', '\x2', '\x2', 'L', 'N', '\a', 
		'\f', '\x2', '\x2', 'M', 'J', '\x3', '\x2', '\x2', '\x2', 'M', 'K', '\x3', 
		'\x2', '\x2', '\x2', 'M', 'L', '\x3', '\x2', '\x2', '\x2', 'N', '\v', 
		'\x3', '\x2', '\x2', '\x2', 'O', 'P', '\x5', '\xE', '\b', '\x2', 'P', 
		'Q', '\a', '\r', '\x2', '\x2', 'Q', '[', '\x5', '\x10', '\t', '\x2', 'R', 
		'S', '\a', '\xE', '\x2', '\x2', 'S', 'X', '\x5', '\x14', '\v', '\x2', 
		'T', 'U', '\a', '\a', '\x2', '\x2', 'U', 'W', '\x5', '\x14', '\v', '\x2', 
		'V', 'T', '\x3', '\x2', '\x2', '\x2', 'W', 'Z', '\x3', '\x2', '\x2', '\x2', 
		'X', 'V', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', '\x3', '\x2', '\x2', '\x2', 
		'Y', '\\', '\x3', '\x2', '\x2', '\x2', 'Z', 'X', '\x3', '\x2', '\x2', 
		'\x2', '[', 'R', '\x3', '\x2', '\x2', '\x2', '[', '\\', '\x3', '\x2', 
		'\x2', '\x2', '\\', '\r', '\x3', '\x2', '\x2', '\x2', ']', '\x61', '\a', 
		'#', '\x2', '\x2', '^', '\x61', '\a', '\xF', '\x2', '\x2', '_', '\x61', 
		'\a', '\"', '\x2', '\x2', '`', ']', '\x3', '\x2', '\x2', '\x2', '`', '^', 
		'\x3', '\x2', '\x2', '\x2', '`', '_', '\x3', '\x2', '\x2', '\x2', '\x61', 
		'\x64', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', '\a', '\x10', '\x2', 
		'\x2', '\x63', '\x65', '\a', '\"', '\x2', '\x2', '\x64', '\x62', '\x3', 
		'\x2', '\x2', '\x2', '\x64', '\x65', '\x3', '\x2', '\x2', '\x2', '\x65', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\x66', 'g', '\a', '\x11', '\x2', '\x2', 
		'g', 'r', '\x5', '\x12', '\n', '\x2', 'h', 'i', '\a', '\x12', '\x2', '\x2', 
		'i', 'n', '\a', '\"', '\x2', '\x2', 'j', 'k', '\a', '\a', '\x2', '\x2', 
		'k', 'm', '\a', '\"', '\x2', '\x2', 'l', 'j', '\x3', '\x2', '\x2', '\x2', 
		'm', 'p', '\x3', '\x2', '\x2', '\x2', 'n', 'l', '\x3', '\x2', '\x2', '\x2', 
		'n', 'o', '\x3', '\x2', '\x2', '\x2', 'o', 'q', '\x3', '\x2', '\x2', '\x2', 
		'p', 'n', '\x3', '\x2', '\x2', '\x2', 'q', 's', '\a', '\x13', '\x2', '\x2', 
		'r', 'h', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\x3', '\x2', '\x2', '\x2', 
		's', '\x8D', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\a', '\x14', '\x2', 
		'\x2', 'u', '\x80', '\x5', '\x12', '\n', '\x2', 'v', 'w', '\a', '\x12', 
		'\x2', '\x2', 'w', '|', '\a', '\"', '\x2', '\x2', 'x', 'y', '\a', '\a', 
		'\x2', '\x2', 'y', '{', '\a', '\"', '\x2', '\x2', 'z', 'x', '\x3', '\x2', 
		'\x2', '\x2', '{', '~', '\x3', '\x2', '\x2', '\x2', '|', 'z', '\x3', '\x2', 
		'\x2', '\x2', '|', '}', '\x3', '\x2', '\x2', '\x2', '}', '\x7F', '\x3', 
		'\x2', '\x2', '\x2', '~', '|', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x81', 
		'\a', '\x13', '\x2', '\x2', '\x80', 'v', '\x3', '\x2', '\x2', '\x2', '\x80', 
		'\x81', '\x3', '\x2', '\x2', '\x2', '\x81', '\x8D', '\x3', '\x2', '\x2', 
		'\x2', '\x82', '\x83', '\a', '\x15', '\x2', '\x2', '\x83', '\x8D', '\a', 
		'\"', '\x2', '\x2', '\x84', '\x85', '\a', '\x16', '\x2', '\x2', '\x85', 
		'\x8D', '\a', '\"', '\x2', '\x2', '\x86', '\x87', '\a', '\x17', '\x2', 
		'\x2', '\x87', '\x89', '\a', '\"', '\x2', '\x2', '\x88', '\x8A', '\a', 
		'\x18', '\x2', '\x2', '\x89', '\x88', '\x3', '\x2', '\x2', '\x2', '\x89', 
		'\x8A', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8D', '\x3', '\x2', '\x2', 
		'\x2', '\x8B', '\x8D', '\a', '\x19', '\x2', '\x2', '\x8C', '\x66', '\x3', 
		'\x2', '\x2', '\x2', '\x8C', 't', '\x3', '\x2', '\x2', '\x2', '\x8C', 
		'\x82', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x84', '\x3', '\x2', '\x2', 
		'\x2', '\x8C', '\x86', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8B', '\x3', 
		'\x2', '\x2', '\x2', '\x8D', '\x11', '\x3', '\x2', '\x2', '\x2', '\x8E', 
		'\x8F', '\a', '\"', '\x2', '\x2', '\x8F', '\x13', '\x3', '\x2', '\x2', 
		'\x2', '\x90', '\x91', '\a', '\"', '\x2', '\x2', '\x91', '\x92', '\a', 
		'\x1A', '\x2', '\x2', '\x92', '\x93', '\x5', '\x16', '\f', '\x2', '\x93', 
		'\x15', '\x3', '\x2', '\x2', '\x2', '\x94', '\x95', '\a', '\x1B', '\x2', 
		'\x2', '\x95', '\xB0', '\a', '\"', '\x2', '\x2', '\x96', '\x97', '\a', 
		'\x1C', '\x2', '\x2', '\x97', '\xB0', '\a', '\"', '\x2', '\x2', '\x98', 
		'\x99', '\a', '\x1D', '\x2', '\x2', '\x99', '\xB0', '\a', '\"', '\x2', 
		'\x2', '\x9A', '\xA1', '\a', '\x1E', '\x2', '\x2', '\x9B', '\xA2', '\a', 
		'\"', '\x2', '\x2', '\x9C', '\x9D', '\a', '\x12', '\x2', '\x2', '\x9D', 
		'\x9E', '\a', '\"', '\x2', '\x2', '\x9E', '\x9F', '\a', '\x10', '\x2', 
		'\x2', '\x9F', '\xA0', '\a', '\"', '\x2', '\x2', '\xA0', '\xA2', '\a', 
		'\x13', '\x2', '\x2', '\xA1', '\x9B', '\x3', '\x2', '\x2', '\x2', '\xA1', 
		'\x9C', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA5', '\x3', '\x2', '\x2', 
		'\x2', '\xA3', '\xA4', '\a', '\x1F', '\x2', '\x2', '\xA4', '\xA6', '\a', 
		'\"', '\x2', '\x2', '\xA5', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xA5', 
		'\xA6', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xB0', '\x3', '\x2', '\x2', 
		'\x2', '\xA7', '\xA8', '\a', ' ', '\x2', '\x2', '\xA8', '\xAB', '\a', 
		'\"', '\x2', '\x2', '\xA9', '\xAA', '\a', '\x1F', '\x2', '\x2', '\xAA', 
		'\xAC', '\a', '\"', '\x2', '\x2', '\xAB', '\xA9', '\x3', '\x2', '\x2', 
		'\x2', '\xAB', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xB0', '\x3', 
		'\x2', '\x2', '\x2', '\xAD', '\xAE', '\a', '!', '\x2', '\x2', '\xAE', 
		'\xB0', '\a', '\"', '\x2', '\x2', '\xAF', '\x94', '\x3', '\x2', '\x2', 
		'\x2', '\xAF', '\x96', '\x3', '\x2', '\x2', '\x2', '\xAF', '\x98', '\x3', 
		'\x2', '\x2', '\x2', '\xAF', '\x9A', '\x3', '\x2', '\x2', '\x2', '\xAF', 
		'\xA7', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xAD', '\x3', '\x2', '\x2', 
		'\x2', '\xB0', '\x17', '\x3', '\x2', '\x2', '\x2', '\x17', '\x1E', '%', 
		',', '\x34', '\x39', '\x44', 'M', 'X', '[', '`', '\x64', 'n', 'r', '|', 
		'\x80', '\x89', '\x8C', '\xA1', '\xA5', '\xAB', '\xAF',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Engage.parsing
