//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/grammarware/projects/engage/Engage/parsing/Engage.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Engage.parsing {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IEngageListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class EngageBaseListener : IEngageListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.engSpec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEngSpec([NotNull] EngageParser.EngSpecContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.engSpec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEngSpec([NotNull] EngageParser.EngSpecContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.typeDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDecl([NotNull] EngageParser.TypeDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.typeDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDecl([NotNull] EngageParser.TypeDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.superType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSuperType([NotNull] EngageParser.SuperTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.superType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSuperType([NotNull] EngageParser.SuperTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.tokenDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTokenDecl([NotNull] EngageParser.TokenDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.tokenDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTokenDecl([NotNull] EngageParser.TokenDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.lexeme"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLexeme([NotNull] EngageParser.LexemeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.lexeme"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLexeme([NotNull] EngageParser.LexemeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.handlerDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHandlerDecl([NotNull] EngageParser.HandlerDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.handlerDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHandlerDecl([NotNull] EngageParser.HandlerDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.trigger"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrigger([NotNull] EngageParser.TriggerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.trigger"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrigger([NotNull] EngageParser.TriggerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.reaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReaction([NotNull] EngageParser.ReactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.reaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReaction([NotNull] EngageParser.ReactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] EngageParser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] EngageParser.NameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] EngageParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] EngageParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperation([NotNull] EngageParser.OperationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperation([NotNull] EngageParser.OperationContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Engage.parsing
