//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/grammarware/projects/engage/Engage/parsing/Engage.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Engage.parsing {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="EngageParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.CLSCompliant(false)]
public interface IEngageListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.engSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEngSpec([NotNull] EngageParser.EngSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.engSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEngSpec([NotNull] EngageParser.EngSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.typeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDecl([NotNull] EngageParser.TypeDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.typeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDecl([NotNull] EngageParser.TypeDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.superType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSuperType([NotNull] EngageParser.SuperTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.superType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSuperType([NotNull] EngageParser.SuperTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.tokenDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTokenDecl([NotNull] EngageParser.TokenDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.tokenDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTokenDecl([NotNull] EngageParser.TokenDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.lexeme"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLexeme([NotNull] EngageParser.LexemeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.lexeme"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLexeme([NotNull] EngageParser.LexemeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.handlerDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHandlerDecl([NotNull] EngageParser.HandlerDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.handlerDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHandlerDecl([NotNull] EngageParser.HandlerDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.trigger"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrigger([NotNull] EngageParser.TriggerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.trigger"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrigger([NotNull] EngageParser.TriggerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.reaction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReaction([NotNull] EngageParser.ReactionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.reaction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReaction([NotNull] EngageParser.ReactionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] EngageParser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] EngageParser.NameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.flag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFlag([NotNull] EngageParser.FlagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.flag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFlag([NotNull] EngageParser.FlagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] EngageParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] EngageParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EngageParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperation([NotNull] EngageParser.OperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EngageParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperation([NotNull] EngageParser.OperationContext context);
}
} // namespace Engage.parsing
